### ISSUE TITLE
add cli option

### ISSUE THREAD

**Issue by beatfreaker** [karuppiah7890/easy-pdf-merge#2]
add cli script so that i can install this module globally and can merge PDF's using command line.

if you want i can create PR for the same ?

**Comment by karuppiah7890** [comment]
@beatfreaker Hey! Nice that you wanna create a CLI script for this module. Even I thought about this. It's just that this module is build using [PDFBox Java Library](pdfbox.apache.org), which itself has a [CLI](https://pdfbox.apache.org/2.0/commandline.html). And I merge PDFs by executing the CLI commands under the hood, and provide it as a npm module for developers, to use it as a simple code.

But yeah, one advantage of the CLI you are gonna make over PDFBox CLI will be - users can type just a word to merge PDFs and they won't even have to bother downloading PDFBox library or anything or know anything about Java or JARs etc. And oh yeah, if you make the CLI, do create a PR to change the README.md too, to make the users aware of the CLI. And in the README.md, you need to mention that they need to have Java 6 or above installed. And the command `java` should work in their CLI.

**Comment by karuppiah7890** [comment]
Fixed by https://github.com/karuppiah7890/easy-pdf-merge/commit/61e02e01ef88021f1b86b20d85bac187c7048ccf but has been currently removed from the package in favor of a separate package https://github.com/karuppiah7890/easy-pdf-merge-cli (not complete) which will use this package
