### ISSUE TITLE
Missing root object specification in trailer.

### ISSUE THREAD

**Issue by elmaurer** [karuppiah7890/easy-pdf-merge#20]
I think this error happens, because there are a few pdfs with different versions and those are not mergable. I'm not sure at all and didn't have time to try it, maybe someone else has a clue. 

> Exception in thread "main" java.io.IOException: Missing root object specification in trailer.
        at org.apache.pdfbox.pdfparser.COSParser.parseTrailerValuesDynamically(COSParser.java:2876)
        at org.apache.pdfbox.pdfparser.PDFParser.initialParse(PDFParser.java:175)
        at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:226)
        at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1070)
        at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:991)
        at org.apache.pdfbox.multipdf.PDFMergerUtility.legacyMergeDocuments(PDFMergerUtility.java:451)
        at org.apache.pdfbox.multipdf.PDFMergerUtility.mergeDocuments(PDFMergerUtility.java:346)
        at org.apache.pdfbox.tools.PDFMerger.merge(PDFMerger.java:70)
        at org.apache.pdfbox.tools.PDFMerger.main(PDFMerger.java:49)
        at org.apache.pdfbox.tools.PDFBox.main(PDFBox.java:81)

`{ Error: Command failed: java -jar  "E:\pdf-service\node_modules\easy-pdf-merge\jar\pdfbox.jar" PDFMerger "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/c05e8e53-4be5-43c0-bae6-b66977640bec.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/p
dfs/7a865998-5557-4329-b51a-69cc3c0644a3.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/downloads/3fb99db2-5a7b-4117-a62a-5f6124ae912a.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/downloads/8da4147a-93ea-452b-95a4-44c58f84b000.pdf" "src/re
s/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/dc9a80ed-2ede-40af-90c7-51f2c193e8cd.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/4dba1a58-c970-4f35-98e2-eee3527d2c08.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/270b993c-0700
-4266-aa33-da42a3535944.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/ef07b229-e4f1-4e4a-b7a0-24690f3d7892.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/downloads/bfacebfc-15c3-407d-a873-f82b09a13870.pdf" "src/res/files/19dcdc5f-0a0d-
48a9-9ce7-479627236df2/pdfs/4d02358f-00af-4348-99e9-35d25dd4c842.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/e7797187-1031-4f51-95df-289fb9722e48.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/downloads/9700122c-c7b5-4bc8-bee7-b8f630
a5f1fa.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/07159c8c-7f97-44d6-99db-1c9a1a442fb0.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/0720ca5a-9963-4745-8040-00794ed244eb.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2
/pdfs/6600befc-7ce7-4326-899f-5cd3926abacd.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/62407c3b-22a0-4419-b9d1-17725bfb03b9.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/da95ef8a-59c8-4d10-a73e-d02ef361ce93.pdf" "src/res/files/
19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/c74e0c9c-5576-41d1-8f1b-f4c15f2b4abf.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/d5a61856-6952-4138-a946-599b8ce121cf.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/81a04cd5-3d09-40f3-b1
30-55b0795f52af.pdf" "src/res/files/19dcdc5f-0a0d-48a9-9ce7-479627236df2/pdfs/e05ddc11-7712-4df2-b1c6-a8cd261078e8.pdf"`
`

**Comment by karuppiah7890** [comment]
No idea. Gotta dig. But I'm busy with other stuff currently. Willing to check PRs

**Comment by elmaurer** [comment]
Seems like the error occurs inside the jar, which gets executed by the module. There might be a solution, if you got some time to check it out: 
https://stackoverflow.com/questions/51485983/apache-pdfbox-merge-error-java-io-ioexception-missing-root-object-specificati

> UPDATE
On the advice of Tilman Hausherr below, I tested the same functionality without using the InputStreams. If I use PDFMergerUtility.addSource(File source) method instead the PDFMergerUtility.addSource(List<InputStream>) the merge works successfully. So it seems as if something with my InputStreams isn't working correctly.
I appreciate any help and am happy to provide more information if needed.

**Comment by elmaurer** [comment]
Alright, my problem was that I wrote too many new files with pdfkit and those were not closed on the merging process. Anyways thanks for your time.

**Comment by karuppiah7890** [comment]
:) 👍

**Comment by karuppiah7890** [comment]
Also, you meant pdfbox right? Or pdfkit?

**Comment by elmaurer** [comment]
Nope, pdfkit. I use it to convert my Images to PDFs before I merge them and somehow the files didn't close like the should.
