### ISSUE TITLE
recursion :_ Stackoverflow error

### ISSUE THREAD

**Issue by alonrez** [karuppiah7890/easy-pdf-merge#24]
when running the script on pdf files with 150 pages or more 
it appears it always throws an stackoverflow error 
i assume it has something to do recursion

```
Error: Command failed: java -jar  "C:\Users\Name\node_modules\easy-pdf-merge\jar\pdfbox.jar" easy-pdf-merge "File1.pdf" 
"File2.pdf" "DestinationFile.pdf"
 Exception in thread "main" java.lang.StackOverflowError

```

**Comment by karuppiah7890** [comment]
Not sure if there's any recursion in the pdfbox library. Gotta check in their issue tracker regarding this issue
