### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by manishrocksag** [karuppiah7890/easy-pdf-merge#25]
I am trying to merge a large number of pdfs around 250 in one go. And I am getting this error. Is there any way to increase the heap size while running the java jar?

**Comment by manishrocksag** [comment]
I have got the solution. In the opts argument you can pass the max heap size option. Something like this in the args for merge ```{ maxBuffer: 1024 * 1000, maxHeap: '1g' }``

**Comment by karuppiah7890** [comment]
Thanks @manishrocksag for bringing this up. I realized I didn't ask the contributors to create docs in the README for these features in their PRs. I have added the docs now here - https://github.com/karuppiah7890/easy-pdf-merge#options . I hope it helps someone else facing similar issues in the future
