### ISSUE TITLE
Got error when merge over 7 PDF files

### ISSUE THREAD

**Issue by Tin-Nguyen** [karuppiah7890/easy-pdf-merge#4]
I got an error when I try to use `easy-pdf-merge` to merge over 5 PDF files

{"cmd":"java -jar \"/node_modules/easy-pdf-merge/jar/pdfbox.jar\" PDFMerger \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484678.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484696.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484711.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484726.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484741.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484756.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484775.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484794.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484813.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484831.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484846.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484861.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484879.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484898.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484917.pdf\" \"/var/folders/yx/3nvjxxb128719bvl9h9jqh680000gn/T/2017-01-15_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484484923.pdf\""}

Do we have a limitation on merging?

**Comment by karuppiah7890** [comment]
Nope. I don't think there's any limitation. I have merged lots of files. And can I know what JSON you have printed here ? Since you have so many double quotes, I think you need to escape a **lot** of em to make the JSON valid

**Comment by Tin-Nguyen** [comment]
@karuppiah7890 , I tried with 5 PDF files, the merging works well. But when I increase to more files, the merging retrieve the error.

The JSON has been retrieved by `easy-pdf-merge`.

**Comment by Tin-Nguyen** [comment]
Do we have a way to see the error detail when we got the error on `merge` function?

>merge(pdfFiles, destFilePath, function(err){
>     if (err) {
>        console.log(err);
>        return;
>    }
>}

**Comment by karuppiah7890** [comment]
Yes, do check the error and put the up over here.

**Comment by Tin-Nguyen** [comment]
I tried to run `java` command to merge the PDFs and it succeed.

`java -jar node_modules/easy-pdf-merge/jar/pdfbox.jar PDFMerger /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676932.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676927.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676919.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676928.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676921.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676922.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676925.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676917.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676926.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676923.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676920.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676931.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676929.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676924.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/2017-01-17_Baskin_Robbins-_Q116-_OLO_FB_PPA-_3.27-6.30_1484676930.pdf /var/folders/kb/ynmw5jys2_ddb7_1qy8x6l7r0000gr/T/output.pdf`

However, if I run by use `easy-pdf-merge` I got the error.

**Comment by Tin-Nguyen** [comment]
I tried to console the log in lib, I got the error

`[Error: stderr maxBuffer exceeded]`

**Comment by Tin-Nguyen** [comment]
I found the solution to fix the issue

http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process

We need to set the max buffer for child process
`exec(command, {maxBuffer: 1024 * 500}, function(error, stdout, stderr){ callback(error, stdout); });`

**Comment by Tin-Nguyen** [comment]
Fixed the issue by enhancing the lib to provide the options

https://github.com/karuppiah7890/easy-pdf-merge/pull/5

@karuppiah7890  please help to review.

**Comment by g0ddish** [comment]
Fixed by #5
