### ISSUE TITLE
JAVA is not recognized as an internal or external command in Window PC

### ISSUE THREAD

**Issue by kgpanteon** [karuppiah7890/easy-pdf-merge#9]
I have installed node module using command:  **npm i easy-pdf-merge**

Added code to the .js file

> var pdfMerger = require('easy-pdf-merge');
> exports.getPdfdemo = function (req, res, next) {
>  pdfMerger(['./businesscard.pdf', './TheBusinessofthe21stCenturyBook.pdf'], './finalpdf.pdf', function (err) {
>     if (err)
>       return console.log(err);
>     console.log('Successfully merged!');
>    });
> };

**Getting below error**

> { Error: Command failed: java -jar "D:\node_projects\project_folder\node_modules\easy-pdf-merge\jar\pdfbox.jar" PDFMerger "./businesscard.pdf" "./TheBusinessofthe21stCenturyBook.pdf" "./finalpdf.pdf"
> 'java' is not recognized as an internal or external command,
> operable program or batch file.
> at ChildProcess.exithandler (child_process.js:275:12)
> at emitTwo (events.js:126:13)
> at ChildProcess.emit (events.js:214:7)
> at maybeClose (internal/child_process.js:925:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
>   killed: false,
>   code: 1,
>   signal: null,
>   cmd: 'java -jar "D:\\node_projects\\project_folder\\node_modules\\easy-pdf-merge\\jar\\pdfbox.jar" PDFMerger "./businesscard.pdf" "./TheBusinessofthe21stCenturyBook.pdf" "./finalpdf.pdf"' }

Please help me to find out the issue.

**Comment by karuppiah7890** [comment]
You need to have Java for this code to run

**Comment by kgpanteon** [comment]
I have installed java see below command line output

> C:\Users\Administrator>java -version
> java version "1.8.0_121"
> Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Node installed in D: and Java in C:.  Also added PATH in environmental variable.
